from .photo_insta_generate_main import insta_photo_generate
from .photo_insta_chats_generate import insta_chats_generate
from .photo_telegram_main_generate import telegram_photo_generate
from .photo_telegram_chats_generate import tg_chats_generate
from .photo_facebook_generate import facebook_photo_generate
from .photo_facebook_chats_generate import fb_chats_generate
from .photo_tiktok_chats_generate import tiktok_chats_generate
from .photo_tiktok_main_generate import tiktok_photo_generate
